"""Adiciona coluna vendas

Revision ID: 742b09a84c99
Revises: 
Create Date: 2024-10-27 15:23:46.995459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '742b09a84c99'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resultado', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vendas', sa.Integer(), nullable=True))
        batch_op.drop_column('vendas_negociacoes')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resultado', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vendas_negociacoes', sa.INTEGER(), nullable=True))
        batch_op.drop_column('vendas')

    # ### end Alembic commands ###
